name: CICD

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build-deploy
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          cd web
          npm install
          npm run build
#      - run: npm test
      - run: bash ./build/deploy-s3.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          WEB_BUCKET: ${{ secrets.WEB_BUCKET }}
